#!/bin/bash

#######################################
# Author: Aminu Mathias
# Program: WinMingle Community C Training
# Description: Generate assembly code in Intel syntax
#######################################

gcc -S "$CFILE" -o arm_assembly.s
